<?php
session_start();
include 'db-connection.php';

// List of tables and their labels
$tables = [
    'members' => 'Members',
    'events' => 'Events',
    'news' => 'News',
    'donations' => 'Donations',
    'comments' => 'Comments',
];

// Table columns and filterable fields
$tableFilters = [
    'members' => [
        'category' => ['type' => 'select'],
        'city' => ['type' => 'select'],
        'state' => ['type' => 'select'],
        'created_at' => ['type' => 'date'],
    ],
    'events' => [
        'date' => ['type' => 'date'],
        'location' => ['type' => 'select'],
    ],
    'news' => [
        'date' => ['type' => 'date'],
        'location' => ['type' => 'select'],
    ],
    'donations' => [
        'payment_method' => ['type' => 'select', 'options' => ['gcash', 'paypal',]],
        'donation_type' => ['type' => 'select', 'options' => ['one_time', 'monthly']],
        'created_at' => ['type' => 'date'],
    ],
    'comments' => [
        'page' => ['type' => 'select'],
        'created_at' => ['type' => 'date'],
    ],
];

// Helper: get unique values for a column
function getColumnValues($conn, $table, $column)
{
    $values = [];
    $result = $conn->query("SELECT DISTINCT `$column` FROM `$table` WHERE `$column` IS NOT NULL AND `$column` != ''");
    if ($result) {
        while ($row = $result->fetch_assoc()) {
            $values[] = $row[$column];
        }
    }
    return $values;
}

// Get selected table and filters from query string
$table = $_GET['table'] ?? 'members';
$filters = $_GET;

// Build SQL WHERE clause based on filters
$where = [];
$params = [];
if (isset($tableFilters[$table])) {
    foreach ($tableFilters[$table] as $col => $info) {
        if ($info['type'] === 'select' && !empty($filters[$col])) {
            $where[] = "`$col` = '" . $conn->real_escape_string($filters[$col]) . "'";
        } elseif ($info['type'] === 'date') {
            if (!empty($filters[$col . '_from'])) {
                $where[] = "DATE(`$col`) >= '" . $conn->real_escape_string($filters[$col . '_from']) . "'";
            }
            if (!empty($filters[$col . '_to'])) {
                $where[] = "DATE(`$col`) <= '" . $conn->real_escape_string($filters[$col . '_to']) . "'";
            }
        }
    }
}
$whereClause = $where ? 'WHERE ' . implode(' AND ', $where) : '';

// Fetch data
$data = [];
if (array_key_exists($table, $tables)) {
    $result = $conn->query("SELECT * FROM `$table` $whereClause LIMIT 1000");
    if ($result) {
        while ($row = $result->fetch_assoc()) {
            $data[] = $row;
        }
    }
}

// For filter dropdowns
$filterDropdowns = [];
foreach ($tableFilters[$table] ?? [] as $col => $info) {
    if ($info['type'] === 'select') {
        if (!empty($info['options'])) {
            $filterDropdowns[$col] = $info['options'];
        } else {
            $filterDropdowns[$col] = getColumnValues($conn, $table, $col);
        }
    }
}

// Fetch admin's first and last name for 'Generated by'
$adminFullName = 'Unknown';
if (isset($_SESSION['user_id'])) {
    $adminId = intval($_SESSION['user_id']);
    $stmt = $conn->prepare("SELECT first_name, last_name FROM admin_users WHERE id = ? LIMIT 1");
    $stmt->bind_param("i", $adminId);
    $stmt->execute();
    $stmt->bind_result($firstName, $lastName);
    if ($stmt->fetch()) {
        $adminFullName = trim($firstName . ' ' . $lastName);
    }
    $stmt->close();
}

$conn->close();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background: #f4f4f4;
        }

        .report-container {
            width: 1344px;
            /* Long bond paper width: 8.5in * 96dpi ≈ 816px */
            min-height: 816px;
            /* Long bond paper height: 14in * 96dpi ≈ 1344px */
            margin: 20px auto;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 16px #0002;
            padding: 40px 24px 40px 24px;
            position: relative;
        }

        @media print {
            .report-container {
                height: 8.3in;
                min-width: 13.8in;
                max-height: 8.5in;
                max-width: 14in;
                padding: 0.4in 0.3in 0.4in 0.3in;
                box-shadow: none;
                border-radius: 0;
            }

            body {
                background: #fff !important;
            }
        }

        .report-header {
            display: flex;
            align-items: center;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 18px;
            margin-bottom: 32px;
        }

        .report-header img {
            width: 70px;
            height: 70px;
            object-fit: contain;
            margin-right: 24px;
        }

        .report-header .church-info {
            flex: 1;
        }

        .report-header .church-info h2 {
            margin: 0;
            font-size: 2.1rem;
            font-weight: 700;
            color: #2d3a4a;
        }

        .report-header .church-info p {
            margin: 0;
            font-size: 1.1rem;
            color: #555;
        }

        .report-title {
            text-align: center;
            font-size: 1.5rem;
            font-weight: 600;
            margin-bottom: 18px;
            color: #2d3a4a;
        }

        .report-filters {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;


            align-items: flex-end;
            justify-content: flex-start;
        }

        .report-filters select,
        .report-filters input[type=date] {
            min-width: 160px;
            margin-bottom: 0;
        }

        .table-responsive {
            margin-top: 18px;
        }

        .table th,
        .table td {
            font-size: 0.98rem;
        }

        .table th.donor-name-col,
        .table td.donor-name-col {
            max-width: 120px;
            width: 120px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .table th.email-col,
        .table td.email-col {
            max-width: 90px;
            width: 90px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .table th.phone-col,
        .table td.phone-col {
            max-width: 110px;
            width: 110px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        @media (max-width: 900px) {
            .report-container {
                width: 98vw;
                padding: 18px 2vw 18px 2vw;
            }

            .report-filters {
                flex-direction: column;
                gap: 10px;
            }
        }

        .filter-cont {
            display: flex;
            gap: 10px;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f8f9fa;
            padding: 20px;
        }
    </style>
</head>

<body>
    <form method="get" class="report-filters">
        <div class="filter-cont">
            <input type="hidden" name="table" value="<?php echo htmlspecialchars($table); ?>">
            <?php foreach ($tableFilters[$table] ?? [] as $col => $info): ?>
                <?php if ($info['type'] === 'select'): ?>
                    <select name="<?php echo $col; ?>" class="form-select" onchange="this.form.submit()">
                        <option value="">All <?php echo ucfirst(str_replace('_', ' ', $col)); ?></option>
                        <?php foreach ($filterDropdowns[$col] as $val): ?>
                            <option value="<?php echo htmlspecialchars($val); ?>" <?php if (($filters[$col] ?? '') == $val) echo 'selected'; ?>><?php echo htmlspecialchars($val); ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php elseif ($info['type'] === 'date'): ?>
                    <input type="date" name="<?php echo $col; ?>_from" value="<?php echo htmlspecialchars($filters[$col . '_from'] ?? ''); ?>" class="form-control" onchange="this.form.submit()" placeholder="From">
                    <input type="date" name="<?php echo $col; ?>_to" value="<?php echo htmlspecialchars($filters[$col . '_to'] ?? ''); ?>" class="form-control" onchange="this.form.submit()" placeholder="To">
                <?php endif; ?>
            <?php endforeach; ?>
            <select name="table" class="form-select" onchange="this.form.submit()" style="max-width:200px;">
                <?php foreach ($tables as $key => $label): ?>
                    <option value="<?php echo $key; ?>" <?php if ($table == $key) echo 'selected'; ?>><?php echo $label; ?></option>
                <?php endforeach; ?>
            </select>
    </form>
    </div>

    <div class="report-container" id="reportContent">
        <div class="report-header">
            <img src="../generated/logo.png" alt="Logo">
            <div class="church-info">
                <h2>Minstrels Rhythm of Hope</h2>
                <p>1675 C. Merced St. Paco, Manila, Philippines</p>
            </div>
        </div>
        <div class="report-title">Report: <?php echo htmlspecialchars($tables[$table]); ?></div>
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px; font-size: 1rem; color: #444;">
            <div>Date Generated: <?php
                                    date_default_timezone_set('Asia/Manila');
                                    echo date('F j, Y, g:i a');
                                    ?></div>
            <div>Generated by: <?php echo htmlspecialchars($adminFullName); ?></div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="reportTable">
                <thead>
                    <tr>
                        <?php if (!empty($data)): ?>
                            <?php foreach (array_keys($data[0]) as $col): ?>
                                <?php
                                // Remove specific columns for members table
                                if ($table === 'members' && in_array(strtolower($col), ['profile_image_type', 'type', 'created_by', 'updated_by'])) continue;
                                // Remove specific columns for events table
                                if ($table === 'events' && in_array(strtolower($col), ['image_type', 'image_path', 'description', 'created_by', 'updated_by'])) continue;
                                if ($table === 'news' && in_array(strtolower($col), ['image_path', 'created_by', 'updated_by'])) continue;
                                // Remove 'message' column for donations table
                                if ($table === 'donations' && strtolower($col) === 'message') continue;
                                $colClass = '';
                                if (in_array(strtolower($col), ['donor_name', 'name'])) $colClass = 'donor-name-col';
                                if (in_array(strtolower($col), ['email', 'donor_email'])) $colClass = 'email-col';
                                if (in_array(strtolower($col), ['phone', 'donor_phone', 'contact'])) $colClass = 'phone-col';
                                ?>
                                <th class="<?php echo $colClass; ?>"><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', $col))); ?></th>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <th>No data found</th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row): ?>
                        <tr>
                            <?php foreach ($row as $col => $val): ?>
                                <?php
                                // Remove specific columns for members table
                                if ($table === 'members' && in_array(strtolower($col), ['profile_image_type', 'type', 'created_by', 'updated_by'])) continue;
                                // Remove specific columns for events table
                                if ($table === 'events' && in_array(strtolower($col), ['image_type', 'image_path', 'description', 'created_by', 'updated_by'])) continue;
                                if ($table === 'news' && in_array(strtolower($col), ['image_path', 'created_by', 'updated_by'])) continue;
                                // Remove 'message' column for donations table
                                if ($table === 'donations' && strtolower($col) === 'message') continue;
                                $colClass = '';
                                if (in_array(strtolower($col), ['donor_name', 'name'])) $colClass = 'donor-name-col';
                                if (in_array(strtolower($col), ['email', 'donor_email'])) $colClass = 'email-col';
                                if (in_array(strtolower($col), ['phone', 'donor_phone', 'contact'])) $colClass = 'phone-col';
                                ?>
                                <?php if (in_array($col, ['profile_image', 'image']) && !empty($val)): ?>
                                    <td class="<?php echo $colClass; ?>"><img src="data:image/jpeg;base64,<?php echo base64_encode($val); ?>" style="max-width:80px;max-height:80px;object-fit:contain;" alt="Image"></td>
                                <?php else: ?>
                                    <td class="<?php echo $colClass; ?>"><?php echo htmlspecialchars($val); ?></td>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div>
    <script src="../lib/html2pdf.bundle.min.js"></script>
    <button id="generatePDF" class="btn btn-success mt-4" style="width:200px;display:block;margin:24px auto 0 auto;">Generate PDF</button>
    <script>
        document.getElementById('generatePDF').addEventListener('click', function() {
            var element = document.getElementById('reportContent');
            // Clone the report content to avoid modifying the original
            var clone = element.cloneNode(true);
            // Remove the Generate PDF button from the clone
            var btn = clone.querySelector('#generatePDF');
            if (btn) btn.parentNode.removeChild(btn);
            // Use html2pdf on the cloned node
            html2pdf().set({
                filename: 'report.pdf',
                image: {
                    type: 'jpeg',
                    quality: 1
                },
                html2canvas: {
                    scale: 4,
                    useCORS: true,
                    allowTaint: true,
                    logging: false,
                    backgroundColor: '#fff',
                },
                jsPDF: {
                    unit: 'in',
                    format: [14, 8.5],
                    orientation: 'landscape'
                }
            }).from(clone).save();
        });
    </script>
</body>

</html>